// <auto-generated />
using System;
using System.Collections.Generic;
using GenesysForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenesysForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenesysForge.Domain.Entities.ArchetypeDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<int>("Brawn")
                        .HasColumnType("integer");

                    b.Property<int>("Cunning")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Intellect")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Presence")
                        .HasColumnType("integer");

                    b.Property<int>("StartingXp")
                        .HasColumnType("integer");

                    b.Property<int>("StrainBase")
                        .HasColumnType("integer");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<int>("Willpower")
                        .HasColumnType("integer");

                    b.Property<int>("WoundBase")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ArchetypeDefs");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CareerDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("CareerSkillNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CareerDefs");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArchetypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Brawn")
                        .HasColumnType("integer");

                    b.Property<Guid>("CareerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cunning")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HeroicAbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Intellect")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCreationPhase")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Presence")
                        .HasColumnType("integer");

                    b.Property<int>("SpentXp")
                        .HasColumnType("integer");

                    b.Property<int>("StrainCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<int>("Willpower")
                        .HasColumnType("integer");

                    b.Property<int>("WoundsCurrent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId");

                    b.HasIndex("CareerId");

                    b.HasIndex("HeroicAbilityId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemDefId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemDefId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("FreeRanks")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCareer")
                        .HasColumnType("boolean");

                    b.Property<int>("Ranks")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillDefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillDefId");

                    b.HasIndex("CharacterId", "SkillDefId")
                        .IsUnique();

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CharacterTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ranks")
                        .HasColumnType("integer");

                    b.Property<Guid>("TalentDefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TalentDefId");

                    b.HasIndex("CharacterId", "TalentDefId")
                        .IsUnique();

                    b.ToTable("CharacterTalents");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.HeroicAbilityDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("HeroicAbilityDefs");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.ItemDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Encumbrance")
                        .HasColumnType("integer");

                    b.Property<int>("EncumbranceThresholdBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("MeleeDefense")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("RangedDefense")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("SoakBonus")
                        .HasColumnType("integer");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ItemDefs");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.SkillDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Characteristic")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SkillDefs");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.TalentDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean");

                    b.Property<int>("MeleeDefenseBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RangedDefenseBonus")
                        .HasColumnType("integer");

                    b.Property<int>("SoakBonus")
                        .HasColumnType("integer");

                    b.Property<int>("StrainBonus")
                        .HasColumnType("integer");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("WoundBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TalentDefs");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.Character", b =>
                {
                    b.HasOne("GenesysForge.Domain.Entities.ArchetypeDef", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Entities.CareerDef", "Career")
                        .WithMany()
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Entities.HeroicAbilityDef", "HeroicAbility")
                        .WithMany()
                        .HasForeignKey("HeroicAbilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Archetype");

                    b.Navigation("Career");

                    b.Navigation("HeroicAbility");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("GenesysForge.Domain.Entities.Character", null)
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDef");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CharacterSkill", b =>
                {
                    b.HasOne("GenesysForge.Domain.Entities.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Entities.SkillDef", "SkillDef")
                        .WithMany()
                        .HasForeignKey("SkillDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillDef");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.CharacterTalent", b =>
                {
                    b.HasOne("GenesysForge.Domain.Entities.Character", null)
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Entities.TalentDef", "TalentDef")
                        .WithMany()
                        .HasForeignKey("TalentDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentDef");
                });

            modelBuilder.Entity("GenesysForge.Domain.Entities.Character", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Skills");

                    b.Navigation("Talents");
                });
#pragma warning restore 612, 618
        }
    }
}
